compiler:
  solc:
    remappings:
      - "@uniswap/v3-periphery=uniswap-v3-periphery@1.0.0"
      - "@uniswap/v3-core=uniswap-v3-core@1.0.0"
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.4.1-solc-0.7-2"
dotenv: .env